# Generated by Django 4.2.2 on 2025-01-20 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Укажите email контакта', max_length=254, verbose_name='email')),
                ('country', models.CharField(help_text='Укажите страну контакта', max_length=100, verbose_name='страна')),
                ('city', models.CharField(help_text='Укажите город контакта', max_length=50, verbose_name='город')),
                ('street', models.CharField(help_text='Укажите улицу контакта', max_length=50, verbose_name='улица')),
                ('building', models.CharField(help_text='Укажите номер дома/строения контакта', max_length=20, verbose_name='номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Укажите название продукта', max_length=100, verbose_name='название')),
                ('type', models.CharField(help_text='Укажите модель продукта', max_length=25, verbose_name='модель')),
                ('date_of_release', models.DateTimeField(auto_now=True, help_text='Укажите дату выхода продукта на рынок', null=True, verbose_name='дата выхода продукта на рынок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Время создания')),
                ('title', models.CharField(help_text='Укажите название поставщика', max_length=100, verbose_name='Название')),
                ('city', models.CharField(help_text='Укажите город контакта', max_length=50, verbose_name='город')),
                ('debt', models.DecimalField(decimal_places=2, help_text='Укажите задолженность перед поставщиком', max_digits=20, verbose_name='Задолженность перед поставщиком')),
                ('level', models.CharField(choices=[(1, 'розничная сеть'), (0, 'завод'), (2, 'индивидуальный предприниматель')])),
                ('contacts', models.ForeignKey(blank=True, help_text='Укажите контакты поставщика', null=True, on_delete=django.db.models.deletion.SET_NULL, to='retailing.contact', verbose_name='Контакты')),
                ('products', models.ManyToManyField(help_text='Укажите продукты поставщика', to='retailing.product', verbose_name='Продукты')),
                ('up_supplier', models.ForeignKey(blank=True, help_text='Укажите поставщика продуктов', null=True, on_delete=django.db.models.deletion.SET_NULL, to='retailing.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
            },
        ),
    ]
